"""empty message

Revision ID: 6ae97d704bd0
Revises: ce1f2c95ea0f
Create Date: 2023-12-12 21:47:34.662542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae97d704bd0'
down_revision = 'ce1f2c95ea0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminfirstname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('adminusername', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('adminemail', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('adminpassword', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adminprofile', sa.String(length=180), nullable=True))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['adminemail'])
        batch_op.create_unique_constraint(None, ['adminusername'])
        batch_op.drop_column('profile')
        batch_op.drop_column('username')
        batch_op.drop_column('firstname')
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.drop_column('adminprofile')
        batch_op.drop_column('adminpassword')
        batch_op.drop_column('adminemail')
        batch_op.drop_column('adminusername')
        batch_op.drop_column('adminfirstname')

    # ### end Alembic commands ###
