"""empty message

Revision ID: 7e9df9b088c5
Revises: 88bb29f7beb1
Create Date: 2024-05-23 22:02:14.039708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9df9b088c5'
down_revision = '88bb29f7beb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registeredusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    with op.batch_alter_table('registeredusers', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
