"""empty message

Revision ID: 88bb29f7beb1
Revises: a32cad382787
Create Date: 2024-05-23 21:59:04.956054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bb29f7beb1'
down_revision = 'a32cad382787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registeredusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    with op.batch_alter_table('registeredusers', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
