"""empty message

Revision ID: 92c7e1b3d990
Revises: 7e9df9b088c5
Create Date: 2024-06-10 21:00:56.236205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92c7e1b3d990'
down_revision = '7e9df9b088c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registeredusers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postalcode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_created')
        batch_op.drop_column('postalcode')
        batch_op.drop_column('address')
        batch_op.drop_column('contact')
        batch_op.drop_column('city')
        batch_op.drop_column('province')
        batch_op.drop_column('country')

    op.create_table('registeredusers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('postalcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('profile', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='registeredusers_pkey'),
    sa.UniqueConstraint('email', name='registeredusers_email_key'),
    sa.UniqueConstraint('username', name='registeredusers_username_key')
    )
    # ### end Alembic commands ###
