"""empty message

Revision ID: d9162ca84603
Revises: dbcef579cabf
Create Date: 2023-12-12 22:17:43.323322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9162ca84603'
down_revision = 'dbcef579cabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.String(length=180), nullable=True))
        batch_op.drop_constraint('admins_adminemail_key', type_='unique')
        batch_op.drop_constraint('admins_adminusername_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('adminemail')
        batch_op.drop_column('adminprofile')
        batch_op.drop_column('adminpassword')
        batch_op.drop_column('adminusername')
        batch_op.drop_column('adminfirstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminfirstname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adminusername', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adminpassword', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adminprofile', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adminemail', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admins_adminusername_key', ['adminusername'])
        batch_op.create_unique_constraint('admins_adminemail_key', ['adminemail'])
        batch_op.drop_column('profile')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
